id: Test_URLhaus
version: 16
vcShouldKeepItemLegacyProdMachine: false
name: Test_URLhaus
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a5e9cd94-d670-433e-81a5-d4f2cc48b1ef
    type: start
    task:
      id: a5e9cd94-d670-433e-81a5-d4f2cc48b1ef
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 9649f6a2-502a-4b8d-8193-801ad362f51e
    type: regular
    task:
      id: 9649f6a2-502a-4b8d-8193-801ad362f51e
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "5"
      - "7"
      - "9"
      - "11"
      - "15"
      - "19"
      - "20"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 904e6915-7b30-4279-8097-f494bd554c6c
    type: regular
    task:
      id: 904e6915-7b30-4279-8097-f494bd554c6c
      version: -1
      name: url - with data
      description: Retrieve URL information from URLhaus
      script: URLhaus|||url
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      url:
        simple: http://ekamjewels.com/anklet/WQG1/?i=1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 87720278-f5ff-4b1e-8e89-079c53ff90d5
    type: condition
    task:
      id: 87720278-f5ff-4b1e-8e89-079c53ff90d5
      version: -1
      name: verify url context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: DBotScore
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: DBotScore.Indicator
                      iscontext: true
                    right:
                      value:
                        simple: http://ekamjewels.com/anklet/WQG1/?i=1
                accessor: Score
            iscontext: true
          right:
            value:
              simple: "2"
      - - operator: hasLength
          left:
            value:
              complex:
                root: URL
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: URL.Data
                      iscontext: true
                    right:
                      value:
                        simple: http://ekamjewels.com/anklet/WQG1/?i=1
                accessor: Tags
            iscontext: true
          right:
            value:
              simple: "5"
      - - operator: hasLength
          left:
            value:
              simple: URL.Relationships
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 8ed102eb-b7f8-49ac-86bb-9cbb6ac9222a
    type: title
    task:
      id: 8ed102eb-b7f8-49ac-86bb-9cbb6ac9222a
      version: -1
      name: complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: fda2d618-356f-4f82-87ca-0acfb5ffb0bf
    type: regular
    task:
      id: fda2d618-356f-4f82-87ca-0acfb5ffb0bf
      version: -1
      name: url - nonexisting
      description: Retrieve URL information from URLhaus
      script: URLhaus|||url
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      url:
        simple: http://gfrewdfsersfsfersfgergre.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: fd9f2a71-9647-4420-8219-aa5a8f64644b
    type: condition
    task:
      id: fd9f2a71-9647-4420-8219-aa5a8f64644b
      version: -1
      name: verify url nonexsiting
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: DBotScore
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: DBotScore.Indicator
                      iscontext: true
                    right:
                      value:
                        simple: http://gfrewdfsersfsfersfgergre.com
                accessor: Score
            iscontext: true
          right:
            value:
              simple: "0"
      - - operator: notContainsGeneral
          left:
            value:
              simple: URL
            iscontext: true
          right:
            value:
              simple: Relationships
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 2e3636f6-8c3f-4b36-85c4-a6811f55be98
    type: regular
    task:
      id: 2e3636f6-8c3f-4b36-85c4-a6811f55be98
      version: -1
      name: domain - with data
      description: Retrieve domain information from URLhaus
      script: URLhaus|||domain
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      domain:
        simple: reunionesdecabales.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 89097b0b-32c2-49cd-8daa-4511005f6ee1
    type: condition
    task:
      id: 89097b0b-32c2-49cd-8daa-4511005f6ee1
      version: -1
      name: verify domain context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: DBotScore
                accessor: Score
            iscontext: true
          right:
            value:
              simple: "1"
      - - operator: isEqualString
          left:
            value:
              simple: Domain.Tags
            iscontext: true
          right:
            value:
              simple: malware
      - - operator: hasLength
          left:
            value:
              simple: Domain.Relationships
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: d8d7c878-b73f-41ec-83e0-5ed07502b4ad
    type: regular
    task:
      id: d8d7c878-b73f-41ec-83e0-5ed07502b4ad
      version: -1
      name: domain - no data
      description: Retrieve domain information from URLhaus
      script: URLhaus|||domain
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      domain:
        simple: google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 91666154-290e-4f85-864e-56ab653ac072
    type: condition
    task:
      id: 91666154-290e-4f85-864e-56ab653ac072
      version: -1
      name: verify context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: DBotScore
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: DBotScore.Indicator
                      iscontext: true
                    right:
                      value:
                        simple: google.com
                accessor: Score
            iscontext: true
          right:
            value:
              simple: "0"
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 2c2a1bdc-c1fb-4076-886e-ff5d2115ba1b
    type: regular
    task:
      id: 2c2a1bdc-c1fb-4076-886e-ff5d2115ba1b
      version: -1
      name: file - no data
      description: Retrieve file information from URLhaus
      script: URLhaus|||file
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      file:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b01
      hash:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b01
      hash_type:
        simple: SHA256
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: d813f3f1-df5f-484c-89f2-beca566cceb4
    type: condition
    task:
      id: d813f3f1-df5f-484c-89f2-beca566cceb4
      version: -1
      name: verify file context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: File.MD5
            iscontext: true
          right:
            value:
              simple: 2ff9cce7a08215ded0945de5965d2a0a
      - - operator: isEqualString
          left:
            value:
              simple: File.SHA256
            iscontext: true
          right:
            value:
              simple: 7855068e0cfb093ab9be9ec172676e3c119e16511f3d631d715a4e77ddad9d89
      - - operator: isEqualString
          left:
            value:
              simple: File.SSDeep
            iscontext: true
          right:
            value:
              simple: 24576:la1QHwgJMrQqj/wAc6QORNx2nAjwkaMm0GV9igWwlnwXQBwfalj21X4GtZ+FdnZ8:vH5qloBMd8A
      - - operator: isEqualString
          left:
            value:
              simple: File.Type
            iscontext: true
          right:
            value:
              simple: dll
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: a5015b1b-8220-418f-802a-79ffca692024
    type: regular
    task:
      id: a5015b1b-8220-418f-802a-79ffca692024
      version: -1
      name: urlhaus-download-sample - with data
      description: Download a malware sample from URLhaus
      script: URLhaus|||urlhaus-download-sample
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      file:
        simple: 254ca6a7a7ef7f17d9884c4a86f88b5d5fd8fe5341c0996eaaf1d4bcb3b2337b
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2630,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 14e331df-04f1-411d-81ca-966cdec93ca6
    type: condition
    task:
      id: 14e331df-04f1-411d-81ca-966cdec93ca6
      version: -1
      name: verify context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: File
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: File.SHA256
                      iscontext: true
                    right:
                      value:
                        simple: 254ca6a7a7ef7f17d9884c4a86f88b5d5fd8fe5341c0996eaaf1d4bcb3b2337b
                accessor: MD5
            iscontext: true
          right:
            value:
              simple: a820381c8acf07cfcb4d9b13498db71d
    view: |-
      {
        "position": {
          "x": 2630,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 6ea02eb5-3bc3-4ace-897b-62af9f2e6046
    type: regular
    task:
      id: 6ea02eb5-3bc3-4ace-897b-62af9f2e6046
      version: -1
      name: urlhaus-download-sample - w/o data
      description: Download a malware sample from URLhaus
      script: URLhaus|||urlhaus-download-sample
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      file:
        simple: 254ca6a7a7ef7f17d9884c4a86f88b5d5fd8fe5341c0996eaaf1d4bcb3b2337c
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 3060,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 11e9be93-baa3-4463-8321-a6ac377ef13d
    type: regular
    task:
      id: 11e9be93-baa3-4463-8321-a6ac377ef13d
      version: -1
      name: file - with data
      description: Retrieve file information from URLhaus
      script: URLhaus|||file
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      file:
        simple: 7855068e0cfb093ab9be9ec172676e3c119e16511f3d631d715a4e77ddad9d89
      hash:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b00
      hash_type:
        simple: SHA256
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: 898c7198-b0bf-4326-842c-21f23704e5f9
    type: condition
    task:
      id: 898c7198-b0bf-4326-842c-21f23704e5f9
      version: -1
      name: verify context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: notContainsGeneral
          left:
            value:
              simple: File
            iscontext: true
          right:
            value:
              simple: Size
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 3390,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
