id: Test_URLhaus
version: 29
vcShouldKeepItemLegacyProdMachine: false
name: Test_URLhaus
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ca5d1dac-c52b-437d-889f-f871dcb32726
    type: start
    task:
      id: ca5d1dac-c52b-437d-889f-f871dcb32726
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 474fe774-bc57-4de9-8797-6750ad6e20c7
    type: regular
    task:
      id: 474fe774-bc57-4de9-8797-6750ad6e20c7
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "5"
      - "7"
      - "9"
      - "11"
      - "15"
      - "19"
      - "20"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 7b17c3bb-c64e-4b98-8c73-8ab93fc92dc7
    type: regular
    task:
      id: 7b17c3bb-c64e-4b98-8c73-8ab93fc92dc7
      version: -1
      name: url - with data
      description: Retrieve URL information from URLhaus
      script: URLhaus|||url
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      url:
        simple: http://ekamjewels.com/anklet/WQG1/?i=1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 8e8becb3-fb97-42c2-8660-378ea17a73a0
    type: condition
    task:
      id: 8e8becb3-fb97-42c2-8660-378ea17a73a0
      version: -1
      name: verify url context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: DBotScore
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: DBotScore.Indicator
                      iscontext: true
                    right:
                      value:
                        simple: http://ekamjewels.com/anklet/WQG1/?i=1
                accessor: Score
            iscontext: true
          right:
            value:
              simple: "2"
      - - operator: hasLength
          left:
            value:
              complex:
                root: URL
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: URL.Data
                      iscontext: true
                    right:
                      value:
                        simple: http://ekamjewels.com/anklet/WQG1/?i=1
                accessor: Tags
            iscontext: true
          right:
            value:
              simple: "5"
      - - operator: hasLength
          left:
            value:
              simple: URL.Relationships
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: bee12209-c400-4def-8da8-a967b53fec8f
    type: title
    task:
      id: bee12209-c400-4def-8da8-a967b53fec8f
      version: -1
      name: complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 7acfd6bd-f596-4e9c-87c9-142f8cab259e
    type: regular
    task:
      id: 7acfd6bd-f596-4e9c-87c9-142f8cab259e
      version: -1
      name: url - nonexisting
      description: Retrieve URL information from URLhaus
      script: URLhaus|||url
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      url:
        simple: http://gfrewdfsersfsfersfgergre.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 2d41f966-c5b4-475b-8695-ecbc2a49185f
    type: condition
    task:
      id: 2d41f966-c5b4-475b-8695-ecbc2a49185f
      version: -1
      name: verify url nonexsiting
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: DBotScore
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: DBotScore.Indicator
                      iscontext: true
                    right:
                      value:
                        simple: http://gfrewdfsersfsfersfgergre.com
                accessor: Score
            iscontext: true
          right:
            value:
              simple: "0"
      - - operator: notContainsGeneral
          left:
            value:
              simple: URL
            iscontext: true
          right:
            value:
              simple: Relationships
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: ae0e113f-f74f-44e8-86e6-13a7eab72165
    type: regular
    task:
      id: ae0e113f-f74f-44e8-86e6-13a7eab72165
      version: -1
      name: domain - with data
      description: Retrieve domain information from URLhaus
      script: URLhaus|||domain
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      domain:
        simple: coin-coin-file-9.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: c294b83e-9ac1-4f24-8dca-fab9d73bdd6b
    type: condition
    task:
      id: c294b83e-9ac1-4f24-8dca-fab9d73bdd6b
      version: -1
      name: verify domain context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: DBotScore
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: DBotScore.Indicator
                      iscontext: true
                    right:
                      value:
                        simple: coin-coin-file-9.com
                accessor: Score
            iscontext: true
          right:
            value:
              simple: "3"
      - - operator: hasLength
          left:
            value:
              complex:
                root: Domain
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: Domain.Name
                      iscontext: true
                    right:
                      value:
                        simple: coin-coin-file-9.com
                accessor: Relationships
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: e721cfa5-5532-4ec7-866c-748256da401b
    type: regular
    task:
      id: e721cfa5-5532-4ec7-866c-748256da401b
      version: -1
      name: domain - no data
      description: Retrieve domain information from URLhaus
      script: URLhaus|||domain
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      domain:
        simple: google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: cc993968-8920-4b09-8e08-881d8117c4b6
    type: condition
    task:
      id: cc993968-8920-4b09-8e08-881d8117c4b6
      version: -1
      name: verify context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: DBotScore
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: DBotScore.Indicator
                      iscontext: true
                    right:
                      value:
                        simple: google.com
                accessor: Score
            iscontext: true
          right:
            value:
              simple: "0"
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: dc4c4d43-0da3-4e8e-85fc-986da121f5c0
    type: regular
    task:
      id: dc4c4d43-0da3-4e8e-85fc-986da121f5c0
      version: -1
      name: file - no data
      description: Retrieve file information from URLhaus
      script: URLhaus|||file
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      file:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b01
      hash:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b01
      hash_type:
        simple: SHA256
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: c1b0b46f-f56d-4cc0-8dc1-4f64c117154f
    type: condition
    task:
      id: c1b0b46f-f56d-4cc0-8dc1-4f64c117154f
      version: -1
      name: verify file context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: File.MD5
            iscontext: true
          right:
            value:
              simple: 2ff9cce7a08215ded0945de5965d2a0a
      - - operator: isEqualString
          left:
            value:
              simple: File.SHA256
            iscontext: true
          right:
            value:
              simple: 7855068e0cfb093ab9be9ec172676e3c119e16511f3d631d715a4e77ddad9d89
      - - operator: isEqualString
          left:
            value:
              simple: File.SSDeep
            iscontext: true
          right:
            value:
              simple: 24576:la1QHwgJMrQqj/wAc6QORNx2nAjwkaMm0GV9igWwlnwXQBwfalj21X4GtZ+FdnZ8:vH5qloBMd8A
      - - operator: isEqualString
          left:
            value:
              simple: File.Type
            iscontext: true
          right:
            value:
              simple: dll
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: ab7178a5-faa9-461e-80fc-92921fa18312
    type: regular
    task:
      id: ab7178a5-faa9-461e-80fc-92921fa18312
      version: -1
      name: urlhaus-download-sample - with data
      description: Download a malware sample from URLhaus
      script: URLhaus|||urlhaus-download-sample
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      file:
        simple: c0e8e6f210186eddae9e30690aad94099277d7991e130c666426cbc1b813bd12
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2630,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 943265e0-2c0e-4a08-83e4-4ad8e83901a6
    type: condition
    task:
      id: 943265e0-2c0e-4a08-83e4-4ad8e83901a6
      version: -1
      name: verify context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: File
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: File.SHA256
                      iscontext: true
                    right:
                      value:
                        simple: c0e8e6f210186eddae9e30690aad94099277d7991e130c666426cbc1b813bd12
                accessor: MD5
            iscontext: true
          right:
            value:
              simple: c3d0754022504ca34bf165a933666b11
    view: |-
      {
        "position": {
          "x": 2630,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 3604f2c0-c08e-4bbd-8abb-61535c2a23bf
    type: regular
    task:
      id: 3604f2c0-c08e-4bbd-8abb-61535c2a23bf
      version: -1
      name: urlhaus-download-sample - w/o data
      description: Download a malware sample from URLhaus
      script: URLhaus|||urlhaus-download-sample
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      file:
        simple: 254ca6a7a7ef7f17d9884c4a86f88b5d5fd8fe5341c0996eaaf1d4bcb3b2337c
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 3060,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: ce15537f-48cb-4c82-8c6d-057115a1ac74
    type: regular
    task:
      id: ce15537f-48cb-4c82-8c6d-057115a1ac74
      version: -1
      name: file - with data
      description: Retrieve file information from URLhaus
      script: URLhaus|||file
      type: regular
      iscommand: true
      brand: URLhaus
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      file:
        simple: 7855068e0cfb093ab9be9ec172676e3c119e16511f3d631d715a4e77ddad9d89
      hash:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b00
      hash_type:
        simple: SHA256
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: 61bcf6a0-11aa-42c8-8c9a-737095dbd6ae
    type: condition
    task:
      id: 61bcf6a0-11aa-42c8-8c9a-737095dbd6ae
      version: -1
      name: verify context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: notContainsGeneral
          left:
            value:
              simple: File
            iscontext: true
          right:
            value:
              simple: Size
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 3390,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
